### ISSUE TITLE
components using FcurveParamDef needs to be update to store to dict

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter_classic_components#13]
all components using FCurveParamDef needs to be updated in order to be exportable

Related issue: https://github.com/mgear-dev/mgear_core/issues/12

**Comment by miquelcampos** [comment]
@jdrese updated the remaining components in #14 #17 #18 #19

**Comment by miquelcampos** [comment]
Remaining components:
spine_S_shape_01
spine_ik_01
spine_ik_02

**Comment by jdrese** [comment]
Thanks Miquel
