### ISSUE TITLE
shifter_classic_components: New Component: Hair Stack Chain

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter_classic_components#32]
Special chain component for hair

- this component can be stack in order to control several chains (slaves) with one master chain
- the connection can be using local axis or world align
- the Master chain should have at less same segments as the biggest of the slaves. But the slaves can have same or less
- Tip and mid control  twist, and scale  (wide and depth)

**Comment by jdrese** [comment]
Seems nice
