### ISSUE TITLE
shifter_classic_components: add new upv roll control to arm_2jnt 

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter_classic_components#36]
The request is to have something similar to this example:
https://vimeo.com/258674376

**Comment by jdrese** [comment]
Wondering how that behaves when animated. My guess is that you end up having less keys to deal with but way more back and forward while posing than usual systems. Nice to have.

**Comment by miquelcampos** [comment]
@jdrese  It is a request from our animSup. Provably I will implementer first in a version 2.0 and later if  the addition works as expected I will consolidate it as an optional feature

**Comment by miquelcampos** [comment]
Change new control functionality to work as an offset value of the roll channel. Not moving the upv_ctl
