### ISSUE TITLE
shifter_classic_components: issue with arm 2jnt_01

### ISSUE THREAD

**Issue by adamavery** [mgear-dev/shifter_classic_components#37]
There seems to be an issue with the orientation of the arm_R0_jnt (the first joint of the right arm component) when the roundness attribute is used. 
The left arm seems fine but this issue happens on the biped guide or If I create a new arm 2jnt_01 component.(see attached image
![curvy_arm_2jnta](https://user-images.githubusercontent.com/46025023/50680787-e2a4b400-1000-11e9-9a19-e135960685a8.jpg)
)

**Comment by adamavery** [comment]
Seems to happen on mGear 3.0 and previous version (2.5.24)

**Comment by miquelcampos** [comment]
Thanks @adamavery 
I know this issue . I was thinking it was fixed here: https://github.com/mgear-dev/shifter_classic_components/issues/35

I will check again ;)

**Comment by adamavery** [comment]
many thanks Miquel :-)

**Comment by miquelcampos** [comment]
Hi @adamavery  I think the issue was fixed on a later version.

![image](https://user-images.githubusercontent.com/1050212/50744634-3cf37e00-1268-11e9-91ae-c1cd3790f236.png)

The latest beta release is from Dec 8th but the #35 fix is from Dec 25th ;)

Cheers,
Miquel
