### ISSUE TITLE
shifter_classic_components: spine_S_shape rename bug

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter_classic_components#50]
This was reported in the forum:  http://forum.mgear-framework.com/t/spine-s-shape-01-settings-mgear-3-1-1/529/4
```
Checking guide
Get options
Get controllers
Get components
spine_C0 (spine_S_shape_01)
Find recursive in  [ 0:00:00.068000 ]
Get parenting for: spine_C0
Guide loaded from hierarchy in  [ 0:00:00.070000 ]
# Traceback (most recent call last):
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\guide.py", line 1024, in updateComponentName
#     guide.updateProperties(self.root, newName, newSide, newIndex)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\guide.py", line 917, in updateProperties
#     comp_guide.rename(root, newName, newSide, newIndex)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\component\guide.py", line 486, in rename
#     self.parent, oldName, oldSideIndex)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\core\dag.py", line 223, in findComponentChildren2
#     return [pm.PyNode(x) for x in children]
#   File "C:\Program Files\Autodesk\Maya2018\Python\lib\site-packages\pymel\core\general.py", line 2282, in __new__
#     raise _objectError(name)
# pymel.core.general.MayaNodeError: Maya Node does not exist (or is not unique):: u'spine_C0_crv'
```

**Comment by darrickyee** [comment]
FYI, this still seems bugged in 3.2.0, although it isn't causing a hard error.

1. Add a spine_S_shape_01 to the guide
2. Rename it in Settings and hit enter

For most components, this seems to automatically rename the required nodes, but for this component, the names don't change (just the "CompName" attribute in the root transform node gets changed).  Then when building, it says "The guide doesn't seem to be up to date.Check logged messages and update the guide" and stops.

One workaround is to select all of the component's nodes, then rename their prefixes using Modify -> Search and Replace Names.  That seems to enable building...

**Comment by miquelcampos** [comment]
@darrickyee  Thanks for the feedback. 
And yes this is something in long overdue :(
