### ISSUE TITLE
Shifter_classic_components: new arm and leg with elbow and knee thickness control

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter_classic_components#53]
A new variant of the default components in the biped template to support thickness in the articulations

- arm_2jnt_03
- leg_2jnt_02

**Comment by tokejepsen** [comment]
Cool, is it possible to show in a gif or something?

**Comment by miquelcampos** [comment]
![elbowThickness](https://user-images.githubusercontent.com/1050212/58234915-a9d06600-7d7a-11e9-8145-df65a68461ec.gif)
@tokejepsen  the components form Miles (arm_ms_2jnt and leg_ms_2jnt also have similar behavior. But this version is moving only the lower part of the limb and have direct control)

**Comment by tokejepsen** [comment]
Very neat with the auto thickness. Guessing its for chunky arms/legs?

**Comment by miquelcampos** [comment]
yep! but not limited to chunky characters. With a little value can help any design
