### ISSUE TITLE
arm_2jnt_04: wrist align and plane normal

### ISSUE THREAD

**Issue by tokejepsen** [mgear-dev/shifter_classic_components#59]
**Problem**

When using the wrist align feature, the wrist and the elbow can get twisted resulting in flipping.

![Capture](https://user-images.githubusercontent.com/1860085/60496864-94205b80-9cab-11e9-9084-d1cb8b972a9f.PNG)

**Comment by tokejepsen** [comment]
The problem is with the calculated [normal](https://github.com/mgear-dev/shifter_classic_components/blob/master/scripts/mgear/shifter_classic_components/arm_2jnt_04/__init__.py#L27), which does not take into account the rotation of the wrist.

My vector skills are not very good, so I'll need some help with this. I'm trying to setup a simple reproducible code, where I can visualize the problem and try to solve but I'm hitting a wall already with converting a vector to a rotation/matrix;
```
import pymel.core as pm

from mgear.core import primitive, vector, transform


guides = ["arm_L0_root", "arm_L0_elbow", "arm_L0_wrist"]
guides = [pm.PyNode(x) for x in guides]
positions = [x.getTranslation(space="world") for x in guides]

normal = vector.getPlaneNormal(positions[0], positions[1], positions[2])
```

**Comment by miquelcampos** [comment]
Hi @tokejepsen 

I will check this as soon as I have a little time.

**Comment by tokejepsen** [comment]
This does not seem to be an issue anymore.

Could be that https://github.com/mgear-dev/shifter_classic_components/pull/58 solved this as well.

**Comment by miquelcampos** [comment]
Hi @tokejepsen  How do you fix it?

**Comment by tokejepsen** [comment]
I honestly dont know, but the issue is not there anymore after rebuilding.

I suspect it might be related to #58.
