### ISSUE TITLE
New Components: UI Slider and Container

### ISSUE THREAD

**Issue by jhoolmans** [mgear-dev/shifter_classic_components#64]
I've combined these two components in this request as they are shown here:

![image](https://user-images.githubusercontent.com/304066/67237789-4000d900-f44c-11e9-8ba1-28c3a516a875.png)

* A container that creates a controller to move around the sliders and builds a border around it's child components.
* Sliders which can be set up to move along the XY plane within the range -1 to 1. Which makes it easy to attach to blendshapes.

Original discussion: [Facial GUI setup](http://forum.mgear-framework.com/t/facial-gui-setup/924/13)

**Comment by miquelcampos** [comment]
this is component will be super useful for many people :)
