### ISSUE TITLE
foot_bk_01 component roll_ctrl issue

### ISSUE THREAD

**Issue by JaschaW** [mgear-dev/shifter_classic_components#68]
**Describe the bug**
When toggling the "use roll control" checkbox under the settings tab of the foot_bk_01 component, it does not update on the actual component.

**To Reproduce**
1. Create foot_bk_01 component
2. Open component settings tab, toggle "use roll ctl" and build.
3. Still builds with roll ctl.

**Screenshots**
![mgear_foot_bk_01](https://user-images.githubusercontent.com/31500795/61631826-a890bc00-ac8b-11e9-82ec-90b30d77ae8a.PNG)

**Solution**
In the component guide module, the method create_componentConnections has a string value "neutralpose" which is the incorrect name. I found that by changing the name to "useRollCtl" as it was named in addParameters method.

![mgear_foot_bk_01_code](https://user-images.githubusercontent.com/31500795/61632031-22c14080-ac8c-11e9-86a1-9cd1f5d4b8ba.PNG)

**Comment by miquelcampos** [comment]
fixed here: https://github.com/mgear-dev/shifter_classic_components/pull/61
